---
#####################################################################################
## Lightning is no Joke around here.
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# https://github.com/CCOSTAN/Home-AssistantConfig/issues/392
# https://www.vcloudinfo.com/2020/08/adding-a-lightning-sensor-to-home-assistant.html
# https://www.youtube.com/watch?v=jwnovbXCrGY
#####################################################################################

sensor:
  - platform: template
    sensors:
      lightning_distance_miles:
        friendly_name: "Lightning Distance"
        unit_of_measurement: 'miles'
        value_template: >
          {% if is_state("sensor.blitzortung_lightning_distance","unknown") -%}
            Unknown
          {% else -%}
            {{ (states("sensor.blitzortung_lightning_distance") | float * 0.621371 )| int}}
          {% endif %}


group:
  Blitzortung Alerts:
    - sensor.blitzortung_lightning_azimuth
    - sensor.blitzortung_lightning_counter
    - sensor.blitzortung_lightning_distance
    - sensor.lightning_distance_miles
    - input_boolean.snooze_lightning



automation:
  - id: '93140ff8-7c59-431b-b6c5-f220a6a4456f'
    alias: Sentry Guard / Weather / Lightning Alerts (25 Miles)
    description: Description text is here
    trigger:
      - platform: numeric_state
        entity_id: sensor.blitzortung_lightning_counter
        above: "0"
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: SNOOZE_LIGHTNING
        id: Snooze Lightning Alerts (Actionable Notification)
      - platform: numeric_state
        entity_id: sensor.lightning_distance_miles
        below: 26
        id: Below 26
    condition:
      - condition: state
        entity_id: input_boolean.snooze_lightning
        state: "off"
    action:
      - service: notify.all
        data: 
          title: Sentry Guard -- Lightning - Lightning Alert!
          message: >
             ߌLightning has been detected within {{(states('sensor.blitzortung_lightning_distance') | int / 1.69) | round (1, 'floor')}} Miles of our home.  Be careful if outdoors.
          data:
            actions:
              - action: SNOOZE_LIGHTNING
                title: Snooze Lightning Alerts
                destructive: true
                authenticationRequired: true
      - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.blitzortung_lightning_counter
              above: "0"
            - condition: numeric_state
              entity_id: sensor.lightning_distance_miles
              below: "26"
          sequence:
            - service: tts.google_say
              data:
                entity_id: media_player.house_speakers
                message: >-
                  Lightning has been detected within {{(states('sensor.blitzortung_lightning_distance') | int / 1.69) | round (1, 'floor')}} Miles of our home,,  Remember lightning can strike any where withing 15 miles of a storm,, Do not use major appliances while an storm is in the area,,  Be careful and weather aware
            - service: button.press
              data: {}
              target:
                entity_id: button.test_light_living_room_61bc3603_identify
            - repeat:
                sequence:
                  - action: button.press
                    metadata: {}
                    data: {}
                    target:
                      entity_id: button.test_light_living_room_61bc3603_identify
                  - service: notify.lg_webos_smart_tv
                    data:
                      message: >-
                        'Lightning has been detected within {{(states('sensor.blitzortung_lightning_distance') | int / 1.69) | round (1, 'floor')}} Miles of our home.  Be careful if outdoors.'
                  - service: tts.google_say
                    data:
                      entity_id: media_player.house_speakers
                      message: >-
                        Lightning has been detected within {{(states('sensor.blitzortung_lightning_distance') | int / 1.69) | round (1, 'floor')}} Miles of our home
#                command_line:
#                  - switch:
#                      name: Home Assistant System Shutdown
#                      command_off: "/usr/sbin/poweroff"
                  - delay: 01:00:00
                until:
                  - condition: numeric_state
                    entity_id: sensor.lightning_distance_miles
                    above: 50
            - service: tts.google_say
              data:
                entity_id: media_player.house_speakers
                message: >-
                  Lightning has been detected within {{(states('sensor.blitzortung_lightning_distance') | int / 1.69) | round (1, 'floor')}} Miles of our home,, I will continue to monitor and track any lighning detections and inform you when they are detected,,, Sentry Guard standing down from lightning alert status!!
        - conditions:
            - condition: trigger
              id: Snooze Lightning Alerts (Actionable Notification)
          sequence:
            - service: input_boolean.turn_on
              data: {}
              target:
                entity_id: input_boolean.snooze_lightning
        default:
          - action: tts.google_say
            metadata: {}
            data:
              entity_id: media_player.house_speakers
              message: Automation didnt function correctly, please check the logs
          - action: tts.cloud_say
            metadata: {}
            data:
              entity_id: media_player.house_speakers
              message: Automation didnt function correctly, please check the logs
    mode: single
    
script:
